-- Flyway migration: create outbox table for reliable event publishing
CREATE TABLE IF NOT EXISTS outbox_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aggregate_type VARCHAR(100) NOT NULL,
  aggregate_id VARCHAR(100) NOT NULL,
  type VARCHAR(200) NOT NULL,
  payload TEXT NOT NULL,
  headers JSONB NULL,
  occurred_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  processed BOOLEAN DEFAULT false NOT NULL,
  processed_at TIMESTAMP WITHOUT TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_outbox_processed ON outbox_event(processed);