-- Flyway migration: create saga table for booking orchestrations
CREATE TABLE IF NOT EXISTS booking_saga (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NULL,
  saga_type VARCHAR(100) NOT NULL,
  state VARCHAR(50) NOT NULL,
  event_key VARCHAR(150) NULL,
  last_error VARCHAR(1000) NULL,
  payload TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_booking_saga_booking_id ON booking_saga(booking_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_booking_saga_type_event_key
  ON booking_saga(saga_type, event_key)
  WHERE event_key IS NOT NULL;
