services:

  # ========================
  # RABBITMQ
  # ========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: thaiquoc
      RABBITMQ_DEFAULT_PASS: 123456

  # ========================
  # PGADMIN (UI quan ly DB)
  # ========================
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - postgres-auth
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # ========================
  # AUTH DB + SERVICE
  # ========================
  postgres-auth:
    image: postgres:15
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: hotel_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quocthai
    volumes:
      - auth_data:/var/lib/postgresql/data

  auth-service:
    build: ./HotelSystem_Backend/HotelSystem_AUTH
    ports:
      - "8081:8081"
    depends_on:
      - postgres-auth
      - rabbitmq
    environment:
      DB_URL: jdbc:postgresql://postgres-auth:5432/hotel_auth
      DB_USERNAME: postgres
      DB_PASSWORD: quocthai
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: thaiquoc
      RABBIT_PASSWORD: 123456

  user-service:
    build: ./HotelSystem_Backend/HotelSystem_USER
    ports:
      - "8082:8082"
    depends_on:
      - postgres-auth
    environment:
      DB_URL: jdbc:postgresql://postgres-auth:5432/hotel_auth
      DB_USERNAME: postgres
      DB_PASSWORD: quocthai


  # ========================
  # ROOM DB + SERVICE
  # ========================
  postgres-room:
    image: postgres:15
    ports:
      - "54323:5432"
    environment:
      POSTGRES_DB: hotel_room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quocthai
    volumes:
      - ./HotelSystem_Backend/HotelSystem_ROOM/pg_hba.conf.dev:/var/lib/postgresql/data/pg_hba.conf
      - room_data:/var/lib/postgresql/data

  room-service:
    build: ./HotelSystem_Backend/HotelSystem_ROOM
    ports:
      - "8083:8083"
    depends_on:
      - postgres-room
      - rabbitmq
    environment:
      DB_URL: jdbc:postgresql://postgres-room:5432/hotel_room
      DB_USERNAME: postgres
      DB_PASSWORD: quocthai
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: thaiquoc
      RABBIT_PASSWORD: 123456
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-local-access-key}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-local-secret-key}
      AWS_REGION: ap-southeast-2
      AWS_S3_BUCKET: ktpmbtl-s3-bucket

  # ========================
  # BOOKING DB + SERVICE
  # ========================
  postgres-booking:
    image: postgres:15
    ports:
      - "54324:5432"
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quocthai
    volumes:
      - booking_data:/var/lib/postgresql/data

  booking-service:
    build: ./HotelSystem_Backend/HotelSystem_BOOKING
    ports:
      - "8084:8084"
    depends_on:
      - postgres-booking
      - rabbitmq
    environment:
      DB_URL: jdbc:postgresql://postgres-booking:5432/hotel_booking
      DB_USERNAME: postgres
      DB_PASSWORD: quocthai
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: thaiquoc
      RABBIT_PASSWORD: 123456

  # ========================
  # PAYMENT DB + SERVICE
  # ========================
  postgres-payment:
    image: postgres:15
    ports:
      - "54325:5432"
    environment:
      POSTGRES_DB: hotel_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quocthai
    volumes:
      - payment_data:/var/lib/postgresql/data

  payment-service:
    build: ./HotelSystem_Backend/HotelSystem_PAYMENT
    ports:
      - "8085:8085"
    depends_on:
      - postgres-payment
      - rabbitmq
    environment:
      DB_URL: jdbc:postgresql://postgres-payment:5432/hotel_payment
      DB_USERNAME: postgres
      DB_PASSWORD: quocthai
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: thaiquoc
      RABBIT_PASSWORD: 123456

  # ========================
  # NOTIFICATION DB + SERVICE
  # ========================
  postgres-notification:
    image: postgres:15
    ports:
      - "54326:5432"
    environment:
      POSTGRES_DB: hotel_notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quocthai
    volumes:
      - notification_data:/var/lib/postgresql/data

  notification-service:
    build: ./HotelSystem_Backend/HotelSystem_NOTIFICATION
    ports:
      - "8086:8086"
    depends_on:
      - postgres-notification
      - rabbitmq
    environment:
      DB_URL: jdbc:postgresql://postgres-notification:5432/hotel_notification
      DB_USERNAME: postgres
      DB_PASSWORD: quocthai
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: thaiquoc
      RABBIT_PASSWORD: 123456

  # ========================
  # FRONTEND
  # ========================
  frontend:
    build: ./HotelSystem
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - user-service
      - room-service
      - booking-service
      - payment-service
      - notification-service

volumes:
  pgadmin_data:
  auth_data:
  room_data:
  booking_data:
  payment_data:
  notification_data: