/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        surface: "#ffffff",
        "surface-dim": "#faf7f4",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f4ef",
        "surface-container": "#f3efea",
        "surface-container-high": "#ede8e3",
        "surface-container-highest": "#e6dfd8",
        "surface-variant": "#e8e1db",
        outline: "#d7c8bf",
        "outline-variant": "#eee5df",

        primary: "#ffb694",
        "primary-container": "#ff6a00",
        "primary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#ffb694",
        "inverse-primary": "#a14000",
        "on-primary": "#571f00",
        "on-primary-container": "#571f00",
        "on-primary-fixed": "#351000",
        "on-primary-fixed-variant": "#7b2f00",

        secondary: "#6b5b54",
        "secondary-container": "#efe3dc",
        "secondary-fixed": "#e4e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#2b2320",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474747",

        tertiary: "#9ccaff",
        "tertiary-container": "#009eff",
        "tertiary-fixed": "#d0e4ff",
        "tertiary-fixed-dim": "#9ccaff",
        "on-tertiary": "#003256",
        "on-tertiary-container": "#003357",
        "on-tertiary-fixed": "#001d35",
        "on-tertiary-fixed-variant": "#00497a",

        error: "#b3261e",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#410002",

        "on-surface": "#1f1917",
        "on-surface-variant": "#5a4b44",
        "on-background": "#1f1917",
        "inverse-surface": "#2a2625",
        "inverse-on-surface": "#f7f3f1",
        "surface-tint": "#ffb694",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
}