spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotel_auth}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:quocthai}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8081

jwt.secret=iJXVUFK+5ccfmPvUHI8lY5CcSql77pZUS4gnf887kbM=
#jwt.expiration=86400000
##jwt.refresh-expiration=604800000

jwt.expiration=604800000
jwt.refresh-expiration=2592000000


spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USERNAME:thaiquoc}
spring.rabbitmq.password=${RABBIT_PASSWORD:123456}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thinhxauzai24@gmail.com
spring.mail.password=xwbscvdpbvdejiya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Eureka
spring.application.name=auth-service
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Tracing
management.tracing.sampling.probability=0.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
