global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8761', 'auth-service:8081', 'user-service:8082', 'room-service:8083', 'booking-service:8084', 'payment-service:8085', 'notification-service:8086', 'api-gateway:8080']

  - job_name: 'zipkin'
    metrics_path: /metrics
    static_configs:
      - targets: ['zipkin:9411']
