# =========================
# APPLICATION
# =========================
spring.application.name=room-service
server.port=8083

# =========================
# DATABASE
# =========================
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-room:5432/hotel_room}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# =========================
# SQL INIT
# =========================
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Seed data switch
room.seed.enabled=${ROOM_SEED_ENABLED:false}

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=90000

# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=${RABBIT_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}

# =========================
# AWS S3
# =========================
aws.accessKeyId=${AWS_ACCESS_KEY_ID:local-access-key}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:local-secret-key}
aws.region=${AWS_REGION:ap-southeast-2}
aws.s3.bucket=${AWS_S3_BUCKET:ktpmbtl-s3-bucket}

# =========================
# EUREKA
# =========================
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true

# =========================
# REDIS + CACHE
# =========================
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms
spring.cache.type=redis
