-- ============================================================
-- BOOKING SERVICE - DEMO DATA FOR STAFF CHECK-IN/CHECK-OUT FLOW
-- 10 bookings around current date for testing all key statuses
-- Depends on room-service seed IDs and user-service customer IDs (4..13)
-- ============================================================
TRUNCATE TABLE
    booking_service_lines,
    booking_invoices,
    booking_stays,
    booking_guests,
    booking_items,
    bookings
RESTART IDENTITY CASCADE;


-- ============================================================
-- 1) BOOKINGS (10 cases)
-- ============================================================
INSERT INTO bookings (
    booking_code,
    user_id,
    total_rooms,
    total_guests,
    notes,
    source,
    created_by,
    check_in,
    check_out,
    status,
    created_at,
    confirmed_at,
    primary_guest_id,
    pre_checkin_completed,
    guest_count,
    reservation_expired_at,
    lock_status,
    rate_plan,
    discount_percent,
    refundable,
    allow_modification,
    base_total,
    subtotal,
    tax_amount,
    discount_total,
    price_multiplier,
    final_total,
    total_price,
    currency,
    price_snapshot_version,
    deposit_amount,
    paid_amount,
    payment_type,
    payment_status,
    payment_transaction_id,
    is_holiday_booking,
    non_refundable,
    hold_expires_at,
    cancelled_at,
    cancellation_reason,
    actual_check_in_at,
    actual_check_out_at,
    cleaning_start_at,
    cleaning_end_at
) VALUES
(
    'DEMO-BKG-001', 4, 1, 2,
    'Case CONFIRMED for upcoming check-in',
    'WEB', 'sql-seeder',
    CURRENT_DATE + 1, CURRENT_DATE + 3,
    'CONFIRMED',
    NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day',
    NULL,
    FALSE, 2,
    NULL,
    'CONFIRMED',
    'FLEXIBLE',
    0,
    TRUE,
    TRUE,
    1600000, 1600000, 0, 0, 1.0, 1600000, 1600000,
    'VND',
    1,
    800000,
    800000,
    'DEPOSIT',
    'PAID',
    'TX-DEMO-001',
    FALSE,
    FALSE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-002', 5, 1, 2,
    'Case CHECKED_IN for check-out pending list',
    'ADMIN', 'sql-seeder',
    CURRENT_DATE - 1, CURRENT_DATE + 1,
    'CHECKED_IN',
    NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days',
    NULL,
    TRUE, 2,
    NULL,
    'CONFIRMED',
    'FLEXIBLE',
    0,
    TRUE,
    FALSE,
    1600000, 1600000, 0, 0, 1.0, 1600000, 1600000,
    'VND',
    1,
    800000,
    1600000,
    'FULL',
    'PAID',
    'TX-DEMO-002',
    FALSE,
    FALSE,
    NULL,
    NULL,
    NULL,
    NOW() - INTERVAL '1 day' + INTERVAL '13 hours',
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-003', 6, 1, 2,
    'Case DEPOSIT_PAID in check-in ready list',
    'MOBILE', 'sql-seeder',
    CURRENT_DATE, CURRENT_DATE + 2,
    'DEPOSIT_PAID',
    NOW() - INTERVAL '1 day', NOW() - INTERVAL '8 hours',
    NULL,
    FALSE, 2,
    NULL,
    'CONFIRMED',
    'FLEXIBLE',
    0,
    TRUE,
    TRUE,
    2800000, 2800000, 0, 0, 1.0, 2800000, 2800000,
    'VND',
    1,
    1400000,
    1400000,
    'DEPOSIT',
    'DEPOSITED',
    'TX-DEMO-003',
    FALSE,
    FALSE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-004', 7, 1, 2,
    'Case CHECKOUT_PENDING_PAYMENT with late fee',
    'ADMIN', 'sql-seeder',
    CURRENT_DATE - 1, CURRENT_DATE,
    'CHECKOUT_PENDING_PAYMENT',
    NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days',
    NULL,
    TRUE, 2,
    NULL,
    'CONFIRMED',
    'FLEXIBLE',
    0,
    TRUE,
    FALSE,
    1400000, 1400000, 0, 0, 1.0, 1400000, 1400000,
    'VND',
    1,
    700000,
    1400000,
    'FULL',
    'PAID',
    'TX-DEMO-004',
    FALSE,
    FALSE,
    NULL,
    NULL,
    NULL,
    NOW() - INTERVAL '1 day' + INTERVAL '14 hours',
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-005', 8, 1, 2,
    'Case PENDING_PAYMENT hold not expired',
    'WEB', 'sql-seeder',
    CURRENT_DATE + 2, CURRENT_DATE + 5,
    'PENDING_PAYMENT',
    NOW() - INTERVAL '3 hours', NULL,
    NULL,
    FALSE, 2,
    NOW() + INTERVAL '4 hours',
    'ACTIVE',
    'FLEXIBLE',
    0,
    TRUE,
    TRUE,
    4200000, 4200000, 0, 0, 1.0, 4200000, 4200000,
    'VND',
    1,
    2100000,
    0,
    'DEPOSIT',
    'PENDING',
    NULL,
    FALSE,
    FALSE,
    NOW() + INTERVAL '4 hours',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-006', 9, 1, 2,
    'Case COMPLETED after successful check-out',
    'ADMIN', 'sql-seeder',
    CURRENT_DATE - 3, CURRENT_DATE - 1,
    'COMPLETED',
    NOW() - INTERVAL '6 days', NOW() - INTERVAL '5 days',
    NULL,
    TRUE, 2,
    NULL,
    'CONFIRMED',
    'FLEXIBLE',
    0,
    TRUE,
    FALSE,
    2800000, 2800000, 0, 0, 1.0, 2800000, 2800000,
    'VND',
    1,
    1400000,
    2800000,
    'FULL',
    'PAID',
    'TX-DEMO-006',
    FALSE,
    FALSE,
    NULL,
    NULL,
    NULL,
    NOW() - INTERVAL '3 days' + INTERVAL '14 hours',
    NOW() - INTERVAL '1 day' + INTERVAL '10 hours',
    NOW() - INTERVAL '1 day' + INTERVAL '10 hours',
    NOW() - INTERVAL '1 day' + INTERVAL '12 hours'
),
(
    'DEMO-BKG-007', 10, 1, 3,
    'Case CANCELLED for cancellation/refund list',
    'WEB', 'sql-seeder',
    CURRENT_DATE + 4, CURRENT_DATE + 7,
    'CANCELLED',
    NOW() - INTERVAL '4 days', NOW() - INTERVAL '3 days',
    NULL,
    FALSE, 3,
    NULL,
    'ACTIVE',
    'FLEXIBLE',
    0,
    FALSE,
    TRUE,
    7200000, 7200000, 0, 0, 1.0, 7200000, 7200000,
    'VND',
    1,
    3600000,
    3600000,
    'DEPOSIT',
    'REFUNDED',
    'TX-DEMO-007',
    FALSE,
    TRUE,
    NULL,
    NOW() - INTERVAL '2 days',
    'Khách đổi lịch công tác',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-008', 11, 1, 2,
    'Case NO_SHOW overdue check-in',
    'MOBILE', 'sql-seeder',
    CURRENT_DATE - 2, CURRENT_DATE,
    'NO_SHOW',
    NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days',
    NULL,
    FALSE, 2,
    NULL,
    'ACTIVE',
    'FLEXIBLE',
    0,
    FALSE,
    FALSE,
    2800000, 2800000, 0, 0, 1.0, 2800000, 2800000,
    'VND',
    1,
    1400000,
    1400000,
    'DEPOSIT',
    'NO_SHOW',
    'TX-DEMO-008',
    FALSE,
    TRUE,
    NULL,
    NOW() - INTERVAL '1 day',
    'Không đến nhận phòng',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-009', 12, 1, 3,
    'Case CONFIRMED premium room for room-change test',
    'ADMIN', 'sql-seeder',
    CURRENT_DATE + 1, CURRENT_DATE + 4,
    'CONFIRMED',
    NOW() - INTERVAL '1 day', NOW() - INTERVAL '6 hours',
    NULL,
    FALSE, 3,
    NULL,
    'CONFIRMED',
    'FLEXIBLE',
    0,
    TRUE,
    TRUE,
    13500000, 13500000, 0, 0, 1.0, 13500000, 13500000,
    'VND',
    1,
    6750000,
    6750000,
    'DEPOSIT',
    'PAID',
    'TX-DEMO-009',
    FALSE,
    FALSE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'DEMO-BKG-010', 13, 1, 3,
    'Case PENDING for manual confirmation flow',
    'WEB', 'sql-seeder',
    CURRENT_DATE + 7, CURRENT_DATE + 10,
    'PENDING',
    NOW() - INTERVAL '2 hours', NULL,
    NULL,
    FALSE, 3,
    NOW() + INTERVAL '12 hours',
    'ACTIVE',
    'FLEXIBLE',
    0,
    TRUE,
    TRUE,
    6000000, 6000000, 0, 0, 1.0, 6000000, 6000000,
    'VND',
    1,
    3000000,
    0,
    'DEPOSIT',
    'PENDING',
    NULL,
    FALSE,
    FALSE,
    NOW() + INTERVAL '12 hours',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
);

-- ============================================================
-- 2) BOOKING_ITEMS (linked with room IDs from room data.sql)
-- ============================================================
INSERT INTO booking_items (
    booking_id,
    room_id,
    room_type_id,
    price_per_night_at_booking,
    discount,
    final_price,
    status,
    check_in,
    check_out,
    nights
) VALUES
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-001'), 1, 1, 800000, 0, 1600000, 'ACTIVE', CURRENT_DATE + 1, CURRENT_DATE + 3, 2),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-002'), 3, 1, 800000, 0, 1600000, 'ACTIVE', CURRENT_DATE - 1, CURRENT_DATE + 1, 2),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-003'), 9, 2, 1400000, 0, 2800000, 'ACTIVE', CURRENT_DATE, CURRENT_DATE + 2, 2),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-004'), 10, 2, 1400000, 0, 1400000, 'ACTIVE', CURRENT_DATE - 1, CURRENT_DATE, 1),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-005'), 11, 2, 1400000, 0, 4200000, 'ACTIVE', CURRENT_DATE + 2, CURRENT_DATE + 5, 3),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-006'), 13, 2, 1400000, 0, 2800000, 'ACTIVE', CURRENT_DATE - 3, CURRENT_DATE - 1, 2),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-007'), 14, 4, 2400000, 0, 7200000, 'ACTIVE', CURRENT_DATE + 4, CURRENT_DATE + 7, 3),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-008'), 16, 2, 1400000, 0, 2800000, 'ACTIVE', CURRENT_DATE - 2, CURRENT_DATE, 2),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-009'), 35, 5, 4500000, 0, 13500000, 'ACTIVE', CURRENT_DATE + 1, CURRENT_DATE + 4, 3),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-010'), 28, 3, 2000000, 0, 6000000, 'ACTIVE', CURRENT_DATE + 7, CURRENT_DATE + 10, 3);

-- ============================================================
-- 3) BOOKING_GUESTS (1 primary guest / booking)
-- ============================================================
INSERT INTO booking_guests (
    booking_id,
    room_id,
    full_name,
    date_of_birth,
    phone,
    email,
    cccd,
    note,
    type,
    primary_guest,
    check_in_person
) VALUES
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-001'), 1, 'Nguyễn Tấn Thịnh', '2004-11-06', '0397994524', 'nguyentanthinh@gmail.com', '079920000001', 'Primary guest seed', 'ADULT', TRUE, FALSE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-002'), 3, 'Trần Minh Châu', '2001-02-18', '0397994525', 'minhchau@gmail.com', '079920000002', 'Primary guest seed', 'ADULT', TRUE, TRUE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-003'), 9, 'Lê Quang Huy', '1999-09-24', '0397994526', 'quanghuy@gmail.com', '079920000003', 'Primary guest seed', 'ADULT', TRUE, FALSE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-004'), 10, 'Phạm Thùy Linh', '2002-07-12', '0397994527', 'thuylinh@gmail.com', '079920000004', 'Primary guest seed', 'ADULT', TRUE, TRUE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-005'), 11, 'Nguyễn Anh Kiệt', '2000-03-03', '0397994528', 'anhkiet@gmail.com', '079920000005', 'Primary guest seed', 'ADULT', TRUE, FALSE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-006'), 13, 'Võ Ngọc Ánh', '2003-12-27', '0397994529', 'ngocanh@gmail.com', '079920000006', 'Primary guest seed', 'ADULT', TRUE, TRUE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-007'), 14, 'Bùi Duy Thành', '1998-05-15', '0397994530', 'duythanh@gmail.com', '079920000007', 'Primary guest seed', 'ADULT', TRUE, FALSE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-008'), 16, 'Đặng Mai Hoàng', '2001-10-09', '0397994531', 'maihoang@gmail.com', '079920000008', 'Primary guest seed', 'ADULT', TRUE, FALSE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-009'), 35, 'Trịnh Bảo Trân', '2005-01-21', '0397994532', 'baotran@gmail.com', '079920000009', 'Primary guest seed', 'ADULT', TRUE, FALSE),
((SELECT id FROM bookings WHERE booking_code = 'DEMO-BKG-010'), 28, 'Phan Khôi Minh', '2002-08-30', '0397994533', 'khoiminh@gmail.com', '079920000010', 'Primary guest seed', 'ADULT', TRUE, FALSE);

-- Sync primary_guest_id into bookings
UPDATE bookings b
SET primary_guest_id = g.id
FROM booking_guests g
WHERE g.booking_id = b.id
  AND g.primary_guest = TRUE;

-- ============================================================
-- 4) BOOKING_STAYS (only active/finished stays)
-- ============================================================
INSERT INTO booking_stays (
    booking_id,
    actual_check_in_at,
    checked_in_by_staff_id,
    representative_guest_id,
    representative_full_name,
    representative_phone,
    representative_cccd,
    actual_check_out_at,
    checked_out_by_staff_id,
    early_checkout_reason,
    late_checkout_minutes,
    late_checkout_fee,
    late_checkout_payment_status,
    used_nights,
    charge_nights,
    unused_nights,
    refund_rate,
    refund_amount,
    checkout_verified_manual_override,
    checkout_verification_override_reason
) VALUES
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-002'),
    NOW() - INTERVAL '1 day' + INTERVAL '13 hours',
    2,
    (SELECT g.id FROM booking_guests g JOIN bookings b ON g.booking_id = b.id WHERE b.booking_code = 'DEMO-BKG-002' AND g.primary_guest = TRUE),
    'Trần Minh Châu', '0397994525', '079920000002',
    NULL, NULL, NULL,
    0, 0, 'NONE',
    2, 2, 0,
    0, 0,
    FALSE, NULL
),
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-004'),
    NOW() - INTERVAL '1 day' + INTERVAL '14 hours',
    2,
    (SELECT g.id FROM booking_guests g JOIN bookings b ON g.booking_id = b.id WHERE b.booking_code = 'DEMO-BKG-004' AND g.primary_guest = TRUE),
    'Phạm Thùy Linh', '0397994527', '079920000004',
    NULL, NULL, NULL,
    30, 150000, 'PENDING',
    1, 1, 0,
    0, 0,
    FALSE, NULL
),
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-006'),
    NOW() - INTERVAL '3 days' + INTERVAL '14 hours',
    2,
    (SELECT g.id FROM booking_guests g JOIN bookings b ON g.booking_id = b.id WHERE b.booking_code = 'DEMO-BKG-006' AND g.primary_guest = TRUE),
    'Võ Ngọc Ánh', '0397994529', '079920000006',
    NOW() - INTERVAL '1 day' + INTERVAL '10 hours',
    3,
    'Checkout đúng giờ',
    0, 0, 'NONE',
    2, 2, 0,
    0, 0,
    FALSE, NULL
);

-- ============================================================
-- 5) BOOKING_SERVICE_LINES (for checkout/invoice service totals)
-- ============================================================
INSERT INTO booking_service_lines (
    booking_id,
    stay_id,
    name,
    quantity,
    unit_price,
    line_total,
    added_by_staff_id,
    created_at
) VALUES
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-002'),
    (SELECT s.id FROM booking_stays s JOIN bookings b ON s.booking_id = b.id WHERE b.booking_code = 'DEMO-BKG-002'),
    'Laundry', 2, 80000, 160000, 2, NOW() - INTERVAL '6 hours'
),
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-004'),
    (SELECT s.id FROM booking_stays s JOIN bookings b ON s.booking_id = b.id WHERE b.booking_code = 'DEMO-BKG-004'),
    'Mini bar', 1, 120000, 120000, 2, NOW() - INTERVAL '3 hours'
),
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-006'),
    (SELECT s.id FROM booking_stays s JOIN bookings b ON s.booking_id = b.id WHERE b.booking_code = 'DEMO-BKG-006'),
    'Airport transfer', 1, 350000, 350000, 3, NOW() - INTERVAL '1 day'
);

-- ============================================================
-- 6) BOOKING_INVOICES (for invoice listing screen)
-- ============================================================
INSERT INTO booking_invoices (
    booking_id,
    amount,
    currency,
    lines_json,
    created_at
) VALUES
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-006'),
    3150000,
    'VND',
    '[{"type":"room","name":"Room charge","amount":2800000},{"type":"service","name":"Airport transfer","amount":350000}]',
    NOW() - INTERVAL '1 day'
),
(
    (SELECT b.id FROM bookings b WHERE b.booking_code = 'DEMO-BKG-004'),
    1670000,
    'VND',
    '[{"type":"room","name":"Room charge","amount":1400000},{"type":"late_fee","name":"Late checkout fee","amount":150000},{"type":"service","name":"Mini bar","amount":120000}]',
    NOW() - INTERVAL '2 hours'
);
